# This is a basic workflow to help you get started with Actions

name: AutoDeploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
       
      - name: SFTP Deploy
      - uses: wlixcc/SFTP-Deploy-Action@1.1
        with:
          # username
          username: ${{ secrets.SFTP_USERNAME }}
          # your sftp server
          server: ${{ secrets.SFTP_HOSTNAME }}
          # your sftp server port, default to 22
          port: ${{ secrets.SFTP_PORT }}
          # you can copy private_key from your *.pem file, keep format
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # will put all file under this path
          local_path: './*'
          # files will copy to under remote_path
          remote_path: '/home/${{ secrets.SFTP_USERNAME }}/public_html/grocery-list/'
          # sftp args
          # args: # optional
